- hosts: all
  tasks:
  - name: installing package1
    package:
      name: "{{ package1 }}"
      state: present
  - name: installing package2
    package: 
      name: "{{ package2 }}"
      state: present
  - name: installing package3
    package: 
      name: "{{ package3 }}"
      state: present
     
