- name: create user and groups
  hosts: all
  tasks:
    - name: create the groups
      group:
        name: "{{ item }}"
        state: present
      with_items:
        - supers1
        - developers1
